version: '3.9'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf
  
  k6:
    container_name: k6
    image: loadimpact/k6
    volumes:
      - ./scripts:/scripts